config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true
  has_many :messages

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html

      format.json{@new_message = @messages.where('id > ?', params[:id])}
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html{redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def index
    if  params[:keyword].present?
      @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    else
      @users = []
    end

    respond_to do |format|
      format.html
      format.json
    end
  end


  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result
  .chat-group-form__field.clerfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "menbers"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users
        #chat-group-user-22.chat-group-user.clearfix
          %input{:name => "group[user_ids][]", :type => "hidden", :value => current_user.id}/
          =current_user.name
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper

  = render '/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_message.html.haml
.message-wrapper{data: {id: message.id}}
  %p.wrapper__main__body__chat_comment_name
    = message.user.name
  %p.wrapper__main__body__chat_comment_time
    = message.created_at.strftime("%Y/%m/%d %H:%M")
  - if message.content.present?
    %p.wrapper__main__body__chat_comment_text
      = message.content
  .image-a
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
.wrapper
 .wrapper__side
  .wrapper__side__header
   %p
    =current_user.name
   = link_to edit_user_path(current_user) do
    = fa_icon 'cog', class: 'icon'
   = link_to new_group_path do
    = fa_icon 'pencil-square-o', class: 'icon'
  .wrapper__side__groups
   - current_user.groups.each do |group|
    .wrapper__side__groups__room
     = link_to group_messages_path(group) do
      .group__name
       = group.name
      .group__message
       = group.show_last_message
 .wrapper__main
  .wrapper__main__header
   .wrapper__main__header__contents
    %h2
     =@group.name
    = link_to edit_group_path(current_user) do
     Edit
    %p
     -@group.users.each do |user|
      =user.name

  .wrapper__main__body
   .wrapper__main__body__chat
    = render @messages
   .wrapper__main__body__submit
    .wrapper__main__body__submit__text
     = form_for [@group, @message], id: "new_message" do |f|
      = f.text_field :content, placeholder: 'type a message', class: "textbox"
      .form__mask
       = f.label :image do
        = fa_icon 'picture-o', class: 'fa-image'
        = f.file_field :image, class: 'hidden'
      = f.submit 'Send', class: 'button'

app/views/tweets/index.html.haml
%header
 %p グループを作成しました。
%div.wrapper
 %div.wrapper__side
  %div.wrapper__side__header
   %p Aki
   %a.fa.fa-cog
   %a.fa.fa-edit
  %div.wrapper__side__groups
   %div.wrapper__side__groups__room
    %h3 独り言
    %p なんだかな〜〜
 %div.wrapper__main
  %div.wrapper__main__header
   %div.wrapper__main__header__contents
    %h2 独り言
    %a Edit
    %p なんだかな〜〜

  %div.wrapper__main__body
   %div.wrapper__main__body__chat
    %p.wrapper__main__body__chat_comment_name Aki
    %p.wrapper__main__body__chat_comment_time 2019/02/05(Fri) 18:54:34
    %p.wrapper__main__body__chat_comment_text なんだかな〜〜
   %div.wrapper__main__body__submit
    %div.wrapper__main__body__submit__text
     %input(placeholder = "type a message")
     %a.fa.fa-image
    %a.button Send

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'